[package]
name = "authentication"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-cors = "0.2.0"
env_logger = "0.7.1"
serde = "1.0.114"
listenfd = "0.3"
tokio = { version = "0.2", features = ["full"] }
actix-web-static-files = "2.0"

[build-dependencies]
actix-web-static-files = "2.0"
